### ISSUE TITLE
License in Cargo metadata disagrees with COPYING file.

### ISSUE THREAD

**Issue by emberian** [Kerosene2000/Reustmann#1]
The metadata should read GPL-3.0.

Additionally, the statement "All rights goes to the dave miller Iota machine." is really confusing. What rights? You should just take it out, and cite it as inspiration.

**Comment by Kerollmops** [comment]
What do you mean by "The metadata" ?

**Comment by emberian** [comment]
Cargo.toml

**Comment by Kerollmops** [comment]
Thanks, 1b2fd768db5edfd790cdabb739dfddad3082cc91
